ALTER TABLE USERS ADD COLUMN lsPointsActive INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsReflective INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsVisual INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsVerbal INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsSequential INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsGlobal INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsIntuitive INT NOT NULL DEFAULT 0;
ALTER TABLE USERS ADD COLUMN lsPointsSensor INT NOT NULL DEFAULT 0;
